### ISSUE TITLE
Development conditionals

### ISSUE THREAD

**Issue by alex88** [WearyMonkey/ngtemplate-loader#32]
Hi there, I'm not sure it's the correct place to ask for help but probably is something this library could help do,

in js, within webpack with the define plugin you can do:
```
if (__DEVELOPMENT__) {}
```

this code is completely removed from build because it will be interpreted as `if(false)`, you think it's possible to do the same with this plugin?

Like conditionally include the html for debugging purposes (e.g. dev only buttons) and the source template is removed from build too? Not just hidden from angular?

**Comment by WearyMonkey** [comment]
@alex88 I don't think that is with in the scope of this loader. Because loaders can be chained and combined easily, it's best for loaders to focus on their core features.

Sounds like what you want is a loader to sit in front of ngtemplate loader, something like:
`require('dev-conditions!ngetmplate!html!./foo.html')`

Not sure if such a plugin exists. If not, maybe you could write one? Writing loaders is very easy :)

**Comment by alex88** [comment]
@WearyMonkey thanks for the fast response, I'm not sure if a loader should do the work or something like that, maybe this can be solved just by a template loader, something that lets me inline javascript in the html? I'll dig more, thanks
